# Generated by Django 3.1.1 on 2020-09-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('is_visible', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='rssfeed',
            name='categories',
            field=models.ManyToManyField(to='rss.Category'),
        ),
    ]
