# Generated by Django 3.1.1 on 2020-09-02 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0002_auto_20200902_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rssfeed',
            name='categories',
            field=models.ManyToManyField(blank=True, to='rss.Category'),
        ),
    ]
