# Generated by Django 3.1.1 on 2020-09-02 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0003_auto_20200902_1526'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='rssfeed',
            options={'verbose_name': 'RSS Feed', 'verbose_name_plural': 'RSS Feeds'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_visible',
        ),
    ]
